import { QuickAction, MessageTemplate, QuickReply } from '@/types';

export const quickActions: QuickAction[] = [
  {
    id: '1',
    type: 'parking_alert',
    title: 'Parking Alert',
    icon: 'AlertTriangle',
    color: '#FFA502',
    message: 'Your car might get a parking ticket! The meter is about to expire.',
  },
  {
    id: '2',
    type: 'blocking',
    title: 'Blocking Entry',
    icon: 'Ban',
    color: '#FF4757',
    message: "You're blocking my driveway/parking spot. Could you please move your car?",
  },
  {
    id: '3',
    type: 'window_open',
    title: 'Window Open',
    icon: 'Wind',
    color: '#3498DB',
    message: 'Your car window is open. Just wanted to let you know!',
  },
  {
    id: '4',
    type: 'lights_on',
    title: 'Lights On',
    icon: 'Lightbulb',
    color: '#FFB800',
    message: 'Your car lights are still on. Battery might drain!',
  },
  {
    id: '5',
    type: 'keys_visible',
    title: 'Keys Visible',
    icon: 'Key',
    color: '#FF6B7A',
    message: 'I can see your keys on the roof/hood/inside. Please check!',
  },
  {
    id: '6',
    type: 'trunk_open',
    title: 'Trunk Open',
    icon: 'Package',
    color: '#00D68F',
    message: 'Your trunk is open/ajar. Just letting you know!',
  },
  {
    id: '7',
    type: 'gas_cap',
    title: 'Gas Cap',
    icon: 'Fuel',
    color: '#4A00E0',
    message: 'Your gas cap is open or missing.',
  },
  {
    id: '8',
    type: 'flat_tire',
    title: 'Flat Tire',
    icon: 'AlertCircle',
    color: '#FF4757',
    message: 'Your tire looks flat or low on air.',
  },
  {
    id: '9',
    type: 'brake_light',
    title: 'Brake Light Out',
    icon: 'Zap',
    color: '#FFA502',
    message: 'Your brake light appears to be out.',
  },
  {
    id: '10',
    type: 'child_pet_alert',
    title: 'Child/Pet Alert',
    icon: 'Heart',
    color: '#FF0000',
    message: 'URGENT: Child/pet seen alone in vehicle. Checking if everything is okay.',
  },
  {
    id: '11',
    type: 'break_in_alert',
    title: 'Security Alert',
    icon: 'Shield',
    color: '#FF0000',
    message: 'Someone was seen near your vehicle. Security has been notified.',
  },
  {
    id: '12',
    type: 'tow_warning',
    title: 'Tow Warning',
    icon: 'Truck',
    color: '#FF4757',
    message: 'Tow truck is in the area. Your vehicle may be at risk.',
  },
  {
    id: '13',
    type: 'street_cleaning',
    title: 'Street Cleaning',
    icon: 'Droplets',
    color: '#3498DB',
    message: 'Street cleaning scheduled. Please move your vehicle.',
  },
  {
    id: '14',
    type: 'for_sale',
    title: 'Interested in Car',
    icon: 'DollarSign',
    color: '#00D68F',
    message: "I'm interested in your car. Is it for sale?",
  },
  {
    id: '15',
    type: 'marketplace',
    title: 'Marketplace Inquiry',
    icon: 'ShoppingBag',
    color: '#4A00E0',
    message: "Hi! I saw your listing and I'm interested. Is it still available?",
  },
  {
    id: '16',
    type: 'service_ad',
    title: 'Service Request',
    icon: 'Wrench',
    color: '#FF6B7A',
    message: "Hi! I need automotive services. Are you available?",
  },
  {
    id: '17',
    type: 'report_driver',
    title: 'Report Driver',
    icon: 'Users',
    color: '#FF0000',
    message: 'Reporting unsafe driving behavior. License plate and details have been documented.',
  },
  {
    id: '18',
    type: 'general',
    title: 'General Message',
    icon: 'MessageCircle',
    color: '#8E2DE2',
    message: '',
  },
  {
    id: '19',
    type: 'vehicle_alarm',
    title: 'Vehicle Alarm',
    icon: 'Bell',
    color: '#FF6B35',
    message: 'Your car alarm is going off. Just wanted to let you know!',
  },
  {
    id: '20',
    type: 'leaking_fluid',
    title: 'Leaking Fluid',
    icon: 'Droplets',
    color: '#2E86AB',
    message: 'Your vehicle appears to be leaking fluid. You might want to check it out.',
  },
];

export const goodNeighborTemplates: MessageTemplate[] = [
  {
    id: 'gn1',
    title: 'Window Open',
    content: 'Your rear window is open.',
    type: 'window_open',
    intent: 'courtesy_notice',
    icon: 'Wind',
  },
  {
    id: 'gn2',
    title: 'Keys Spotted',
    content: 'Keys spotted on roof/hood.',
    type: 'keys_visible',
    intent: 'safety_alert',
    icon: 'Key',
  },
  {
    id: 'gn3',
    title: 'Interior Light On',
    content: 'Interior light on - might drain battery.',
    type: 'lights_on',
    intent: 'courtesy_notice',
    icon: 'Lightbulb',
  },
  {
    id: 'gn4',
    title: 'Suspicious Activity',
    content: 'Someone tugging door handles - security notified.',
    type: 'break_in_alert',
    intent: 'emergency',
    icon: 'Shield',
  },
  {
    id: 'gn5',
    title: 'Parking Meter Expiring',
    content: 'Your parking meter is about to expire.',
    type: 'parking_alert',
    intent: 'courtesy_notice',
    icon: 'Clock',
  },
  {
    id: 'gn6',
    title: 'Blocking Driveway',
    content: 'Your vehicle is blocking a driveway.',
    type: 'blocking',
    intent: 'parking_issue',
    icon: 'Ban',
  },
  {
    id: 'gn7',
    title: 'Car Alarm',
    content: 'Your car alarm is going off.',
    type: 'car_alarm',
    intent: 'urgent_notice',
    icon: 'AlertTriangle',
  },
  {
    id: 'gn8',
    title: 'About to Be Towed',
    content: 'Heads up — a tow truck is hooking up to your vehicle right now. Move ASAP!',
    type: 'tow_warning',
    intent: 'emergency',
    icon: 'Truck',
  },
  {
    id: 'gn9',
    title: 'Flat Tire',
    content: 'Your tire looks flat or low on air. You may want to check it before driving.',
    type: 'flat_tire',
    intent: 'safety_alert',
    icon: 'AlertCircle',
  },
  {
    id: 'gn10',
    title: 'Headlights Left On',
    content: 'Your headlights are still on — your battery may drain.',
    type: 'lights_on',
    intent: 'courtesy_notice',
    icon: 'Lightbulb',
  },
  {
    id: 'gn11',
    title: 'Trunk / Hatch Open',
    content: 'Your trunk/hatch is open or not fully closed.',
    type: 'trunk_open',
    intent: 'courtesy_notice',
    icon: 'Package',
  },
  {
    id: 'gn12',
    title: 'Gas Cap Open',
    content: 'Your gas cap is open or missing.',
    type: 'gas_cap',
    intent: 'courtesy_notice',
    icon: 'Fuel',
  },
  {
    id: 'gn13',
    title: 'Leaking Fluid',
    content: 'Your vehicle appears to be leaking fluid underneath.',
    type: 'leaking_fluid',
    intent: 'safety_alert',
    icon: 'Droplets',
  },
  {
    id: 'gn14',
    title: 'Brake Light Out',
    content: 'One of your brake lights appears to be out.',
    type: 'brake_light',
    intent: 'safety_alert',
    icon: 'Zap',
  },
  {
    id: 'gn15',
    title: 'Child / Pet in Car',
    content: 'URGENT: A child or pet is alone in your vehicle. Please return immediately.',
    type: 'child_pet_alert',
    intent: 'emergency',
    icon: 'Heart',
  },
  {
    id: 'gn16',
    title: 'Lights Left On',
    content: 'Your interior or parking lights are still on.',
    type: 'lights_on',
    intent: 'courtesy_notice',
    icon: 'Lightbulb',
  },
  {
    id: 'gn17',
    title: 'Street Cleaning',
    content: 'Street cleaning is scheduled here soon — you may get ticketed.',
    type: 'street_cleaning',
    intent: 'urgent_notice',
    icon: 'Droplets',
  },
  {
    id: 'gn18',
    title: 'Door Not Closed',
    content: 'One of your doors is open or not fully shut.',
    type: 'window_open',
    intent: 'courtesy_notice',
    icon: 'Wind',
  },
  {
    id: 'gn19',
    title: 'Nice Park Job',
    content: 'Just wanted to say — great parking job!',
    type: 'compliment',
    intent: 'courtesy_notice',
    icon: 'Heart',
  },
  {
    id: 'gn20',
    title: 'Hit & Run Witness',
    content: 'Your vehicle appears to have been hit. I have details if you need them.',
    type: 'hazard',
    intent: 'urgent_notice',
    icon: 'AlertTriangle',
  },
];

export const quickReplies: QuickReply[] = [
  {
    id: 'qr1',
    emoji: 'ON',
    text: 'On my way',
    action: 'on_my_way',
  },
  {
    id: 'qr2',
    emoji: 'TY',
    text: 'Thanks',
    action: 'thanks',
  },
  {
    id: 'qr3',
    emoji: 'ID',
    text: 'Not my car',
    action: 'not_my_car',
  },
  {
    id: 'qr4',
    emoji: 'SOS',
    text: 'Call security',
    action: 'call_security',
  },
  {
    id: 'qr5',
    emoji: 'OK',
    text: 'Got it',
    action: 'acknowledge',
  },
];

export const appVariants = [
  {
    id: 'plateping',
    name: 'PlatePing',
    description: 'Consumer app for anonymous vehicle communication',
    features: [
      'Claim your plate',
      'Receive anonymous messages',
      'Quick action replies',
      'Good neighbor alerts',
    ],
  },
  {
    id: 'lotlink',
    name: 'LotLink',
    description: 'Property & campus parking management',
    features: [
      'Parking lot management',
      'Resident registration',
      'Visitor passes',
      'Automated notices',
    ],
  },
  {
    id: 'fleetrelay',
    name: 'FleetRelay',
    description: 'Business fleet communication',
    features: [
      'Fleet registration',
      'Real-time feedback',
      'Driver safety reports',
      'Route optimization',
    ],
  },
  {
    id: 'eventtag',
    name: 'EventTag',
    description: 'Temporary event parking',
    features: [
      'QR code decals',
      'Time-bound messaging',
      'Event coordination',
      'Tailgate meetups',
    ],
  },
  {
    id: 'safecity',
    name: 'SafeCity Relay',
    description: 'Municipal parking alerts',
    features: [
      'Street sweeping alerts',
      'Towing warnings',
      'Break-in cluster alerts',
      'City partnerships',
    ],
  },
];